<?php

namespace company\modules\shop\controllers;

use yii\web\Controller;

/**
 * Default controller for the `shop` module
 */
class BaseShopController extends Controller {
    public function actions() {
      //  $this->layout='@company/modules/shop/views/layouts/main.php';
        return parent::actions(); // TODO: Change the autogenerated stub
    }


}
